server:
  port: 8090

spring:
  application:
    name: pong

logging:
  level:
    root: fatal
    com.mint: info
  file:
    path: run/pong-logs/
    name: ${logging.file.path}log-${server.port}.txt

pong:
  time-window-nano: 1000_000_000