server:
  port: 8080

spring:
  application:
    name: ping
  reactor:
    debug-agent:
      enabled: true

logging:
  level:
    root: info
    com.mint.ping.service.Ping: info
  file:
    path: ping-logs
    name: ${logging.file.path}/log-${server.port}.txt

ping:
  pong-service_url: http://localhost:8090/sayWorld
  request-interval-milliseconds: 1000
  max-fail-number: 5